### ISSUE TITLE
util.get_signs() may get an empty dictionary

### ISSUE THREAD

**Issue by adonis0147** [ten3roberts/qf.nvim#12]
## Description

When jumping to the definition by LSP server, the following errors may occur if there are multiple matched items.

```shell
Error executing vim.schedule lua callback: ...neovim/0.9.1/share/nvim/runtime/lua/vim/lsp/handle
25]..script /.local/share/nvim/lazy/qf.nvim/syntax/qf.vim, line 7: Vim(lua):E5108:
ndex field 'E' (a nil value)
stack traceback:
        .../.local/share/nvim/lazy/qf.nvim/lua/qf/format.lua:32: in function 'setup_synta
        /.local/share/nvim/lazy/qf.nvim/lua/qf.lua:122: in function 'setup_syntax'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_command'
        ...neovim/0.9.1/share/nvim/runtime/lua/vim/lsp/handlers.lua:409: in function 'handler'
        ...w/Cellar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'nvim_command'
        ...neovim/0.9.1/share/nvim/runtime/lua/vim/lsp/handlers.lua:409: in function 'handler'
        ...w/Cellar/neovim/0.9.1/share/nvim/runtime/lua/vim/lsp.lua:1394: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

```lua
-- lua/qf/format.lua
 31   local d = util.get_signs()
 32   local sum = d.E.text .. d.W.text .. d.I.text .. d.N.text .. d.T.text .. " "
 33   syntax_cache = string.format(template, d.E.text, d.W.text, d.I.text, d.N.text, d.T.text,
 34   return syntax_cache
```

In `lua/qf/format.lua`, the [line #31](https://github.com/ten3roberts/qf.nvim/blob/main/lua/qf/format.lua#L31) may get an empty dictionary which causes this issue.

## Workaround

```lua
require('qf').setup { pretty = false }
```

**Comment by ten3roberts** [comment]
I suppose by multiple matches you mean that they land in the quickfix?

Does the quickfix work normally?

**Comment by adonis0147** [comment]
> I suppose by multiple matches you mean that they land in the quickfix?
> 
> Does the quickfix work normally?

Yes, the quickfix works fine. I can jump to the desire line by hitting the enter key in quickfix.

**Comment by ten3roberts** [comment]
How does the quickfix look normally.

The issue appears to be because there are no defintions for `DiagnosticSignError` etc.

That could easily be remedied by falling back to "E", "W" etc.

But if this is spurious it would not be good to have a fallback kick in while the signs *are* defined

**Comment by ten3roberts** [comment]
Does c88956b713395801dcd7d5a9afbf1c5a8b0a99c8 solve your issue?

I managed to reproduce by running make which produced an error message.

**Comment by adonis0147** [comment]
> How does the quickfix look normally.

It appears that the quickfix is used to store the locations of matched items and help users jump to the desired line by selecting it. No diagnostics raise under this scenario.
 
> The issue appears to be because there are no defintions for `DiagnosticSignError` etc.
> 
> That could easily be remedied by falling back to "E", "W" etc.
> 
> But if this is spurious it would not be good to have a fallback kick in while the signs _are_ defined

Yes, the missing definitions cause this issue.

**Comment by adonis0147** [comment]
> Does [c88956b](https://github.com/ten3roberts/qf.nvim/commit/c88956b713395801dcd7d5a9afbf1c5a8b0a99c8) solve your issue?

It works! Thanks for fixing this issue promptly.

> I managed to reproduce by running make which produced a compilation error which was put in the quickfix list

Great!

**Comment by ten3roberts** [comment]
Here is how it looks for me with custom signs using nerd-fonts

![Screenshot 2023-06-28 at 09 48 15](https://github.com/ten3roberts/qf.nvim/assets/25723553/1f7d9eb3-8e11-47ae-be9e-1e9285e24ec3)

And here is how it should look for you without signs
![Screenshot 2023-06-28 at 09 49 12](https://github.com/ten3roberts/qf.nvim/assets/25723553/5fef135f-dc8a-4b27-99bb-f5a7d0ec3654)

Both using `vim.diagnostic.setqflist()`

If there is no *error level* like for an lsp multi match for location or grep no sign is shown

![Screenshot 2023-06-28 at 09 52 24](https://github.com/ten3roberts/qf.nvim/assets/25723553/862a58aa-fc9f-4b05-9a05-ca0458648e0f)

If there are no 'E' signs etc for actual errors feel free to open another issue for that 😊

**Comment by adonis0147** [comment]
> Here is how it looks for me with custom signs using nerd-fonts
> 
> ![Screenshot 2023-06-28 at 09 48 15](https://user-images.githubusercontent.com/25723553/249392780-1f7d9eb3-8e11-47ae-be9e-1e9285e24ec3.png)
> 
> And here is how it should look for you without signs ![Screenshot 2023-06-28 at 09 49 12](https://user-images.githubusercontent.com/25723553/249393031-5fef135f-dc8a-4b27-99bb-f5a7d0ec3654.png)
> 
> Both using `vim.diagnostic.setqflist()`
> 
> If there is no _error level_ like for an lsp multi match for location or grep no sign is shown
> 
> ![Screenshot 2023-06-28 at 09 52 24](https://user-images.githubusercontent.com/25723553/249393898-862a58aa-fc9f-4b05-9a05-ca0458648e0f.png)
> 
> If there are no 'E' signs etc for actual errors feel free to open another issue for that 😊

The behavior looks good to me. Thank you for all the help!
